index:
    path: /{filter_slug}
    controller: App\Controller\DefaultController::index
    defaults:
      filter_slug: null
    requirements:
      filter_slug: 'favourite'

login:
  path: /prihlasit
  controller: App\Controller\SecurityController::login
  methods: GET|POST

logout:
  path: /logout
  methods: GET

post_add:
  path: /prispevek/pridat
  controller: App\Controller\PostController::new
  methods: GET|POST

post_detail:
  path: /prispevek/{id}
  controller: App\Controller\PostController::detail
  methods: GET

post_delete:
  path: /prispevek/{id}
  controller: App\Controller\PostController::delete
  methods: DELETE

like_post:
  path: /post/{id}/like
  controller: App\Controller\PostController::postLike
  methods: GET

like_post_ajax:
  path: /post/{id}/like
  controller: App\Controller\PostController::postLikeAjax
  methods: POST