index:
    path: /
    controller: App\Controller\DefaultController::index

login:
  path: /prihlasit
  controller: App\Controller\SecurityController::login
  methods: GET|POST

logout:
  path: /logout
  methods: GET

likePost:
  path: /post/{id}/like
  controller: App\Controller\PostController::postLike
  methods: POST